#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Complete the Hodu LaHashem word mappings - 1 Chronicles 16:8-36"""

import json

# Read the existing structure
with open('data/hodu_embedded.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Complete word mappings by ID (w1-w226)
mappings = {
    1: {"trans": "Give thanks", "root": "י-ד-ה"},
    3: {"trans": "call", "root": "ק-ר-א"},
    4: {"trans": "in His name", "root": "ש-מ-ם"},
    5: {"trans": "make known", "root": "י-ד-ע"},
    6: {"trans": "among the nations", "root": "ע-מ-ם"},
    7: {"trans": "His deeds", "root": "ע-ל-ל"},
    8: {"trans": "Sing", "root": "ש-י-ר"},
    10: {"trans": "make music", "root": "ז-מ-ר"},
    12: {"trans": "speak", "root": "ש-י-ח"},
    13: {"trans": "of all", "root": "כ-ל-ל"},
    14: {"trans": "His wonders", "root": "פ-ל-א"},
    15: {"trans": "Glory", "root": "ה-ל-ל"},
    16: {"trans": "in the name of", "root": "ש-מ-ם"},
    17: {"trans": "His holiness", "root": "ק-ד-ש"},
    18: {"trans": "Let rejoice", "root": "ש-מ-ח"},
    19: {"trans": "the heart of", "root": "ל-ב-ב"},
    20: {"trans": "those who seek", "root": "ב-ק-ש"},
    21: {"trans": "Hashem", "root": "ה-ו-ה"},
    22: {"trans": "Seek", "root": "ד-ר-ש"},
    24: {"trans": "and His strength", "root": "ע-ז-ז"},
    25: {"trans": "Seek", "root": "ב-ק-ש"},
    26: {"trans": "His presence", "root": "פ-נ-ה"},
    27: {"trans": "continually", "root": "ת-מ-ד"},
    28: {"trans": "Remember", "root": "ז-כ-ר"},
    29: {"trans": "His wonders", "root": "פ-ל-א"},
    30: {"trans": "which", "root": "א-ש-ר"},
    31: {"trans": "He has done", "root": "ע-ש-ה"},
    32: {"trans": "His wonders", "root": "מ-פ-ת"},
    33: {"trans": "and the judgments of", "root": "ש-פ-ט"},
    34: {"trans": "His mouth", "root": "פ-ה-ה"},
    35: {"trans": "Seed of", "root": "ז-ר-ע"},
    37: {"trans": "His servant", "root": "ע-ב-ד"},
    38: {"trans": "Sons of", "root": "ב-נ-ה"},
    39: {"trans": "Jacob", "root": "י-ע-ק"},
    40: {"trans": "His chosen ones", "root": "ב-ח-ר"},
    43: {"trans": "our God", "root": "א-ל-ה"},
    44: {"trans": "In all", "root": "כ-ל-ל"},
    46: {"trans": "His judgments", "root": "ש-פ-ט"},
    47: {"trans": "Remember", "root": "ז-כ-ר"},
    49: {"trans": "His covenant", "root": "ב-ר-ת"},
    50: {"trans": "the word", "root": "ד-ב-ר"},
    51: {"trans": "He commanded", "root": "צ-ו-ה"},
    52: {"trans": "for a thousand", "root": "א-ל-ף"},
    53: {"trans": "generations", "root": "ד-ו-ר"},
    54: {"trans": "Which", "root": "א-ש-ר"},
    55: {"trans": "He made", "root": "כ-ר-ת"},
    57: {"trans": "Abraham", "root": "א-ב-ר"},
    58: {"trans": "And His oath", "root": "ש-ב-ע"},
    59: {"trans": "to Isaac", "root": "י-צ-ח"},
    60: {"trans": "And He established it", "root": "ע-מ-ד"},
    61: {"trans": "to Jacob", "root": "י-ע-ק"},
    62: {"trans": "as a statute", "root": "ח-ק-ק"},
    64: {"trans": "a covenant", "root": "ב-ר-ת"},
    66: {"trans": "Saying", "root": "א-מ-ר"},
    68: {"trans": "I will give", "root": "נ-ת-נ"},
    70: {"trans": "Canaan", "root": "כ-נ-ע"},
    71: {"trans": "the portion", "root": "ח-ב-ל"},
    72: {"trans": "of your inheritance", "root": "נ-ח-ל"},
    73: {"trans": "When you were", "root": "ה-י-ה"},
    74: {"trans": "few", "root": "מ-ת-ת"},
    75: {"trans": "in number", "root": "ס-פ-ר"},
    76: {"trans": "Very few", "root": "מ-ע-ט"},
    77: {"trans": "and strangers", "root": "ג-ו-ר"},
    78: {"trans": "in it", "root": "ב-ה-ה"},
    79: {"trans": "And they walked", "root": "ה-ל-כ"},
    80: {"trans": "from nation", "root": "ג-ו-י"},
    82: {"trans": "to nation", "root": "ג-ו-י"},
    83: {"trans": "And from one kingdom", "root": "מ-ל-כ"},
    85: {"trans": "people", "root": "ע-מ-ם"},
    86: {"trans": "to another", "root": "א-ח-ר"},
    88: {"trans": "He permitted", "root": "נ-ו-ח"},
    89: {"trans": "to a man", "root": "א-י-ש"},
    90: {"trans": "to oppress them", "root": "ע-ש-ק"},
    91: {"trans": "And He reproved", "root": "י-כ-ח"},
    92: {"trans": "on their behalf", "root": "ע-ל-ה"},
    93: {"trans": "kings", "root": "מ-ל-כ"},
    94: {"trans": "Do not", "root": "א-ל-ל"},
    95: {"trans": "touch", "root": "נ-ג-ע"},
    96: {"trans": "My anointed ones", "root": "מ-ש-ח"},
    97: {"trans": "and to My prophets", "root": "נ-ב-א"},
    98: {"trans": "Do not", "root": "א-ל-ל"},
    99: {"trans": "do harm", "root": "ר-ע-ע"},
    100: {"trans": "Sing", "root": "ש-י-ר"},
    102: {"trans": "all", "root": "כ-ל-ל"},
    104: {"trans": "Proclaim", "root": "ב-ש-ר"},
    105: {"trans": "from day", "root": "י-ו-ם"},
    107: {"trans": "to day", "root": "י-ו-ם"},
    108: {"trans": "His salvation", "root": "י-ש-ע"},
    109: {"trans": "Tell", "root": "ס-פ-ר"},
    110: {"trans": "among the nations", "root": "ג-ו-י"},
    112: {"trans": "His glory", "root": "כ-ב-ד"},
    113: {"trans": "Among all", "root": "כ-ל-ל"},
    114: {"trans": "the peoples", "root": "ע-מ-ם"},
    115: {"trans": "His wonders", "root": "פ-ל-א"},
    116: {"trans": "For", "root": "כ-י-י"},
    117: {"trans": "great", "root": "ג-ד-ל"},
    119: {"trans": "and greatly praised", "root": "ה-ל-ל"},
    120: {"trans": "exceedingly", "root": "מ-א-ד"},
    121: {"trans": "And awesome", "root": "י-ר-א"},
    124: {"trans": "all", "root": "כ-ל-ל"},
    126: {"trans": "For", "root": "כ-י-י"},
    127: {"trans": "all", "root": "כ-ל-ל"},
    129: {"trans": "the peoples", "root": "ע-מ-ם"},
    130: {"trans": "are idols", "root": "א-ל-ל"},
    131: {"trans": "[here", "root": "כ-א-נ"},
    132: {"trans": "one should", "root": "צ-ר-כ"},
    133: {"trans": "pause]", "root": "פ-ס-ק"},
    134: {"trans": "and Hashem", "root": "ה-ו-ה"},
    135: {"trans": "the heavens", "root": "ש-מ-ם"},
    136: {"trans": "He made", "root": "ע-ש-ה"},
    137: {"trans": "Splendor", "root": "ה-ו-ד"},
    138: {"trans": "and majesty", "root": "ה-ד-ר"},
    139: {"trans": "before Him", "root": "פ-נ-ה"},
    140: {"trans": "Strength", "root": "ע-ז-ז"},
    141: {"trans": "and gladness", "root": "ח-ד-ה"},
    142: {"trans": "in His place", "root": "מ-ק-ם"},
    143: {"trans": "Ascribe", "root": "י-ה-ב"},
    145: {"trans": "families of", "root": "ש-פ-ח"},
    146: {"trans": "peoples", "root": "ע-מ-ם"},
    147: {"trans": "Ascribe", "root": "י-ה-ב"},
    149: {"trans": "glory", "root": "כ-ב-ד"},
    150: {"trans": "and strength", "root": "ע-ז-ז"},
    151: {"trans": "Ascribe", "root": "י-ה-ב"},
    153: {"trans": "the glory of", "root": "כ-ב-ד"},
    154: {"trans": "His name", "root": "ש-מ-ם"},
    155: {"trans": "Bring", "root": "נ-ש-א"},
    156: {"trans": "an offering", "root": "מ-נ-ח"},
    157: {"trans": "and come", "root": "ב-ו-א"},
    158: {"trans": "before Him", "root": "פ-נ-ה"},
    159: {"trans": "Bow down", "root": "ש-ח-ה"},
    161: {"trans": "in the splendor of", "root": "ה-ד-ר"},
    162: {"trans": "holiness", "root": "ק-ד-ש"},
    163: {"trans": "Tremble", "root": "ח-י-ל"},
    164: {"trans": "before Him", "root": "פ-נ-ה"},
    165: {"trans": "all", "root": "כ-ל-ל"},
    167: {"trans": "Indeed", "root": "א-פ-ף"},
    168: {"trans": "will be established", "root": "כ-ו-נ"},
    169: {"trans": "the world", "root": "ת-ב-ל"},
    170: {"trans": "it shall not", "root": "ב-ל-ל"},
    171: {"trans": "be moved", "root": "מ-ו-ט"},
    172: {"trans": "Let rejoice", "root": "ש-מ-ח"},
    173: {"trans": "the heavens", "root": "ש-מ-ם"},
    174: {"trans": "and let exult", "root": "ג-י-ל"},
    176: {"trans": "And let them say", "root": "א-מ-ר"},
    177: {"trans": "among the nations", "root": "ג-ו-י"},
    179: {"trans": "reigns", "root": "מ-ל-כ"},
    180: {"trans": "Let roar", "root": "ר-ע-ם"},
    181: {"trans": "the sea", "root": "י-מ-ם"},
    182: {"trans": "and its fullness", "root": "מ-ל-א"},
    183: {"trans": "Let exult", "root": "ע-ל-ץ"},
    184: {"trans": "the field", "root": "ש-ד-ה"},
    186: {"trans": "that", "root": "א-ש-ר"},
    187: {"trans": "is in it", "root": "ב-ו-ו"},
    188: {"trans": "Then", "root": "א-ז-ז"},
    189: {"trans": "shall sing", "root": "ר-נ-נ"},
    190: {"trans": "the trees of", "root": "ע-צ-ץ"},
    191: {"trans": "the forest", "root": "י-ע-ר"},
    192: {"trans": "before", "root": "פ-נ-ה"},
    194: {"trans": "For", "root": "כ-י-י"},
    195: {"trans": "He comes", "root": "ב-ו-א"},
    196: {"trans": "to judge", "root": "ש-פ-ט"},
    198: {"trans": "the earth", "root": "א-ר-ץ"},
    199: {"trans": "Give thanks", "root": "י-ד-ה"},
    200: {"trans": "to Hashem", "root": "ה-ו-ה"},
    201: {"trans": "For", "root": "כ-י-י"},
    202: {"trans": "He is good", "root": "ט-ו-ב"},
    203: {"trans": "For", "root": "כ-י-י"},
    205: {"trans": "His kindness", "root": "ח-ס-ד"},
    206: {"trans": "And say", "root": "א-מ-ר"},
    207: {"trans": "Save us", "root": "י-ש-ע"},
    209: {"trans": "our salvation", "root": "י-ש-ע"},
    210: {"trans": "And gather us", "root": "ק-ב-ץ"},
    211: {"trans": "and deliver us", "root": "נ-צ-ל"},
    213: {"trans": "the nations", "root": "ג-ו-י"},
    214: {"trans": "To give thanks", "root": "י-ד-ה"},
    215: {"trans": "to the name of", "root": "ש-מ-ם"},
    216: {"trans": "Your holiness", "root": "ק-ד-ש"},
    217: {"trans": "To glory", "root": "ש-ב-ח"},
    218: {"trans": "in Your praise", "root": "ה-ל-ל"},
    219: {"trans": "Blessed", "root": "ב-ר-כ"},
    225: {"trans": "and forever", "root": "ע-ד-ד"}
}

# Apply all mappings
for word_id, mapping in mappings.items():
    wid = f"w{word_id}"
    if wid in data['words']:
        data['words'][wid]['translation'] = mapping['trans']
        data['words'][wid]['shoresh'] = {
            'root': mapping['root'],
            'root_letters': list(mapping['root'].split('-')),
            'meaning': mapping['trans'],
            'word_type': 'noun'
        }

# Write back
with open('data/hodu_embedded.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Count completion
total = 226
completed = sum(1 for w in data['words'].values() if w['translation'])
print(f"Hodu mappings: {completed}/{total} words ({100*completed/total:.1f}%)")
print(f"Remaining: {total - completed} words")
