#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Complete Shirat HaYam word mappings - All 237 words of Exodus 15"""

import json

with open('data/shirat_hayam_embedded.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Complete mappings for Exodus 15:1-19 (Az Yashir - Song at the Sea)
# This is one of the most significant texts in Jewish liturgy
mappings = {
    1: {"trans": "Then", "root": "א-ז-ז"},
    2: {"trans": "sang", "root": "ש-י-ר"},
    3: {"trans": "Moses", "root": "מ-ש-ה"},
    4: {"trans": "and the children of", "root": "ב-נ-ה"},
    5: {"trans": "Israel", "root": "י-ש-ר"},
    6: {"trans": "[direct object]", "root": "א-ת-ת"},
    7: {"trans": "the song", "root": "ש-י-ר"},
    8: {"trans": "this", "root": "ז-א-ת"},
    9: {"trans": "to Hashem", "root": "ה-ו-ה"},
    10: {"trans": "And they said", "root": "א-מ-ר"},
    11: {"trans": "saying", "root": "א-מ-ר"},
    12: {"trans": "I will sing", "root": "ש-י-ר"},
    13: {"trans": "to Hashem", "root": "ה-ו-ה"},
    14: {"trans": "for", "root": "כ-י-י"},
    15: {"trans": "He has triumphed", "root": "ג-א-ה"},
    16: {"trans": "gloriously", "root": "ג-א-ה"},
    17: {"trans": "horse", "root": "ס-ו-ס"},
    18: {"trans": "and its rider", "root": "ר-כ-ב"},
    19: {"trans": "He has thrown", "root": "ר-מ-ה"},
    20: {"trans": "into the sea", "root": "י-מ-ם"},
    21: {"trans": "My strength", "root": "ע-ז-ז"},
    22: {"trans": "and song", "root": "ז-מ-ר"},
    23: {"trans": "is God", "root": "י-ה-ה"},
    24: {"trans": "And He became", "root": "ה-י-ה"},
    25: {"trans": "for me", "root": "ל-י-י"},
    26: {"trans": "salvation", "root": "י-ש-ע"},
    27: {"trans": "This", "root": "ז-ה-ה"},
    28: {"trans": "is my God", "root": "א-ל-ל"},
    29: {"trans": "and I will glorify Him", "root": "נ-ו-ה"},
    30: {"trans": "God of", "root": "א-ל-ה"},
    31: {"trans": "my father", "root": "א-ב-ב"},
    32: {"trans": "and I will exalt Him", "root": "ר-ו-ם"},
    33: {"trans": "Hashem", "root": "ה-ו-ה"},
    34: {"trans": "is a man of", "root": "א-י-ש"},
    35: {"trans": "war", "root": "מ-ל-ח"},
    36: {"trans": "Hashem", "root": "ה-ו-ה"},
    37: {"trans": "is His name", "root": "ש-מ-ם"},
    38: {"trans": "chariots of", "root": "מ-ר-כ"},
    39: {"trans": "Pharaoh", "root": "פ-ר-ע"},
    40: {"trans": "and his army", "root": "ח-י-ל"},
    41: {"trans": "He has cast", "root": "י-ר-ה"},
    42: {"trans": "into the sea", "root": "י-מ-ם"},
    43: {"trans": "And the choicest of", "root": "מ-ב-ח"},
    44: {"trans": "his officers", "root": "ש-ל-ש"},
    45: {"trans": "were drowned", "root": "ט-ב-ע"},
    46: {"trans": "in the Sea of", "root": "י-מ-ם"},
    47: {"trans": "Reeds", "root": "ס-ו-ף"},
    48: {"trans": "The depths", "root": "ת-ה-ם"},
    49: {"trans": "covered them", "root": "כ-ס-ה"},
    50: {"trans": "They descended", "root": "י-ר-ד"},
    51: {"trans": "into the depths", "root": "צ-ל-ל"},
    52: {"trans": "like", "root": "כ-מ-ו"},
    53: {"trans": "a stone", "root": "א-ב-נ"},
    54: {"trans": "Your right hand", "root": "י-מ-נ"},
    55: {"trans": "Hashem", "root": "ה-ו-ה"},
    56: {"trans": "is glorious", "root": "א-ד-ר"},
    57: {"trans": "in power", "root": "כ-ח-ח"},
    58: {"trans": "Your right hand", "root": "י-מ-נ"},
    59: {"trans": "Hashem", "root": "ה-ו-ה"},
    60: {"trans": "crushes", "root": "ר-ע-ץ"},
    61: {"trans": "the enemy", "root": "א-י-ב"},
    62: {"trans": "And in the greatness of", "root": "ר-ב-ב"},
    63: {"trans": "Your majesty", "root": "ג-א-ה"},
    64: {"trans": "You destroy", "root": "ה-ר-ס"},
    65: {"trans": "those who rise against You", "root": "ק-ו-ם"},
    66: {"trans": "You send forth", "root": "ש-ל-ח"},
    67: {"trans": "Your wrath", "root": "ח-ר-ה"},
    68: {"trans": "it consumes them", "root": "א-כ-ל"},
    69: {"trans": "like stubble", "root": "ק-ש-ש"},
    70: {"trans": "And with the breath of", "root": "ר-ו-ח"},
    71: {"trans": "Your nostrils", "root": "א-פ-ף"},
    72: {"trans": "were piled up", "root": "ע-ר-ם"},
    73: {"trans": "the waters", "root": "מ-י-ם"},
    74: {"trans": "They stood", "root": "נ-צ-ב"},
    75: {"trans": "like", "root": "כ-מ-ו"},
    76: {"trans": "a heap", "root": "נ-ד-ד"},
    77: {"trans": "the flowing waters", "root": "נ-ז-ל"},
    78: {"trans": "Congealed", "root": "ק-פ-א"},
    79: {"trans": "the depths", "root": "ת-ה-ם"},
    80: {"trans": "in the heart of", "root": "ל-ב-ב"},
    81: {"trans": "the sea", "root": "י-מ-ם"},
    82: {"trans": "Said", "root": "א-מ-ר"},
    83: {"trans": "the enemy", "root": "א-י-ב"},
    84: {"trans": "I will pursue", "root": "ר-ד-ף"},
    85: {"trans": "I will overtake", "root": "נ-ש-ג"},
    86: {"trans": "I will divide", "root": "ח-ל-ק"},
    87: {"trans": "the spoil", "root": "ש-ל-ל"},
    88: {"trans": "My soul shall be filled", "root": "מ-ל-א"},
    89: {"trans": "my soul", "root": "נ-פ-ש"},
    90: {"trans": "I will draw", "root": "ר-י-ק"},
    91: {"trans": "my sword", "root": "ח-ר-ב"},
    92: {"trans": "My hand shall destroy them", "root": "י-ר-ש"},
    93: {"trans": "my hand", "root": "י-ד-ד"},
    94: {"trans": "You blew", "root": "נ-ש-ף"},
    95: {"trans": "with Your wind", "root": "ר-ו-ח"},
    96: {"trans": "covered them", "root": "כ-ס-ה"},
    97: {"trans": "the sea", "root": "י-מ-ם"},
    98: {"trans": "They sank", "root": "צ-ל-ל"},
    99: {"trans": "like lead", "root": "ע-פ-ר"},
    100: {"trans": "in waters", "root": "מ-י-ם"},
    101: {"trans": "mighty", "root": "א-ד-ר"},
    102: {"trans": "Who", "root": "מ-י-י"},
    103: {"trans": "is like You", "root": "כ-מ-ו"},
    104: {"trans": "among the mighty", "root": "א-י-ל"},
    105: {"trans": "Hashem", "root": "ה-ו-ה"},
    106: {"trans": "Who", "root": "מ-י-י"},
    107: {"trans": "is like You", "root": "כ-מ-ו"},
    108: {"trans": "glorious", "root": "א-ד-ר"},
    109: {"trans": "in holiness", "root": "ק-ד-ש"},
    110: {"trans": "awesome", "root": "י-ר-א"},
    111: {"trans": "in praises", "root": "ה-ל-ל"},
    112: {"trans": "doing", "root": "ע-ש-ה"},
    113: {"trans": "wonders", "root": "פ-ל-א"},
    114: {"trans": "You stretched out", "root": "נ-ט-ה"},
    115: {"trans": "Your right hand", "root": "י-מ-נ"},
    116: {"trans": "swallowed them", "root": "ב-ל-ע"},
    117: {"trans": "the earth", "root": "א-ר-ץ"},
    118: {"trans": "You guided", "root": "נ-ח-ה"},
    119: {"trans": "in Your kindness", "root": "ח-ס-ד"},
    120: {"trans": "this people", "root": "ע-מ-ם"},
    121: {"trans": "You redeemed", "root": "ג-א-ל"},
    122: {"trans": "You led", "root": "נ-ה-ל"},
    123: {"trans": "in Your strength", "root": "ע-ז-ז"},
    124: {"trans": "to", "root": "א-ל-ל"},
    125: {"trans": "dwelling place of", "root": "נ-ו-ה"},
    126: {"trans": "Your holiness", "root": "ק-ד-ש"},
    127: {"trans": "Heard", "root": "ש-מ-ע"},
    128: {"trans": "the peoples", "root": "ע-מ-ם"},
    129: {"trans": "they trembled", "root": "ר-ג-ז"},
    130: {"trans": "Pangs", "root": "ח-י-ל"},
    131: {"trans": "seized", "root": "א-ח-ז"},
    132: {"trans": "the inhabitants of", "root": "י-ש-ב"},
    133: {"trans": "Philistia", "root": "פ-ל-ש"},
    134: {"trans": "Then", "root": "א-ז-ז"},
    135: {"trans": "were terrified", "root": "ב-ה-ל"},
    136: {"trans": "the chieftains of", "root": "א-ל-ף"},
    137: {"trans": "Edom", "root": "א-ד-ם"},
    138: {"trans": "the mighty men of", "root": "א-י-ל"},
    139: {"trans": "Moab", "root": "מ-ו-א"},
    140: {"trans": "seized them", "root": "א-ח-ז"},
    141: {"trans": "trembling", "root": "ר-ע-ד"},
    142: {"trans": "Melted", "root": "מ-ו-ג"},
    143: {"trans": "all", "root": "כ-ל-ל"},
    144: {"trans": "the inhabitants of", "root": "י-ש-ב"},
    145: {"trans": "Canaan", "root": "כ-נ-ע"},
    146: {"trans": "Fall", "root": "נ-פ-ל"},
    147: {"trans": "upon them", "root": "ע-ל-ה"},
    148: {"trans": "terror", "root": "א-י-ם"},
    149: {"trans": "and dread", "root": "פ-ח-ד"},
    150: {"trans": "By the greatness of", "root": "ג-ד-ל"},
    151: {"trans": "Your arm", "root": "ז-ר-ע"},
    152: {"trans": "they are still", "root": "ד-מ-ם"},
    153: {"trans": "as stone", "root": "א-ב-נ"},
    154: {"trans": "Until", "root": "ע-ד-ד"},
    155: {"trans": "passes over", "root": "ע-ב-ר"},
    156: {"trans": "Your people", "root": "ע-מ-ם"},
    157: {"trans": "Hashem", "root": "ה-ו-ה"},
    158: {"trans": "Until", "root": "ע-ד-ד"},
    159: {"trans": "passes over", "root": "ע-ב-ר"},
    160: {"trans": "this people", "root": "ע-מ-ם"},
    161: {"trans": "You have acquired", "root": "ק-נ-ה"},
    162: {"trans": "You will bring them", "root": "ב-ו-א"},
    163: {"trans": "and plant them", "root": "נ-ט-ע"},
    164: {"trans": "on the mountain of", "root": "ה-ר-ר"},
    165: {"trans": "Your inheritance", "root": "נ-ח-ל"},
    166: {"trans": "The place", "root": "מ-כ-ן"},
    167: {"trans": "for Your dwelling", "root": "י-ש-ב"},
    168: {"trans": "You made", "root": "פ-ע-ל"},
    169: {"trans": "Hashem", "root": "ה-ו-ה"},
    170: {"trans": "the Sanctuary", "root": "ק-ד-ש"},
    171: {"trans": "my Lord", "root": "א-ד-נ"},
    172: {"trans": "established", "root": "כ-ו-נ"},
    173: {"trans": "Your hands", "root": "י-ד-ד"},
    174: {"trans": "Hashem", "root": "ה-ו-ה"},
    175: {"trans": "will reign", "root": "מ-ל-כ"},
    176: {"trans": "forever", "root": "ע-ל-ם"},
    177: {"trans": "and ever", "root": "ע-ד-ד"},
    178: {"trans": "Hashem", "root": "ה-ו-ה"},
    179: {"trans": "will reign", "root": "מ-ל-כ"},
    180: {"trans": "forever", "root": "ע-ל-ם"},
    181: {"trans": "and ever", "root": "ע-ד-ד"},
    182: {"trans": "Hashem", "root": "ה-ו-ה"},
    183: {"trans": "His kingdom", "root": "מ-ל-כ"},
    184: {"trans": "is established", "root": "ק-י-ם"},
    185: {"trans": "forever", "root": "ע-ל-ם"},
    186: {"trans": "and to the world of", "root": "ע-ל-ם"},
    187: {"trans": "worlds", "root": "ע-ל-ם"},
    188: {"trans": "For", "root": "כ-י-י"},
    189: {"trans": "came", "root": "ב-ו-א"},
    190: {"trans": "the horse of", "root": "ס-ו-ס"},
    191: {"trans": "Pharaoh", "root": "פ-ר-ע"},
    192: {"trans": "with his chariot", "root": "ר-כ-ב"},
    193: {"trans": "and with his horsemen", "root": "פ-ר-ש"},
    194: {"trans": "into the sea", "root": "י-מ-ם"},
    195: {"trans": "And brought back", "root": "ש-ו-ב"},
    196: {"trans": "Hashem", "root": "ה-ו-ה"},
    197: {"trans": "upon them", "root": "ע-ל-ה"},
    198: {"trans": "[direct object]", "root": "א-ת-ת"},
    199: {"trans": "the waters of", "root": "מ-י-ם"},
    200: {"trans": "the sea", "root": "י-מ-ם"},
    201: {"trans": "And the children of", "root": "ב-נ-ה"},
    202: {"trans": "Israel", "root": "י-ש-ר"},
    203: {"trans": "walked", "root": "ה-ל-כ"},
    204: {"trans": "on dry land", "root": "י-ב-ש"},
    205: {"trans": "in the midst of", "root": "ת-ו-כ"},
    206: {"trans": "the sea", "root": "י-מ-ם"},
    207: {"trans": "For", "root": "כ-י-י"},
    208: {"trans": "to Hashem", "root": "ה-ו-ה"},
    209: {"trans": "is the kingdom", "root": "מ-ל-כ"},
    210: {"trans": "And He rules", "root": "מ-ש-ל"},
    211: {"trans": "over the nations", "root": "ג-ו-י"},
    212: {"trans": "And will go up", "root": "ע-ל-ה"},
    213: {"trans": "saviors", "root": "י-ש-ע"},
    214: {"trans": "on Mount", "root": "ה-ר-ר"},
    215: {"trans": "Zion", "root": "צ-י-ן"},
    216: {"trans": "to judge", "root": "ש-פ-ט"},
    217: {"trans": "[direct object]", "root": "א-ת-ת"},
    218: {"trans": "the mountain of", "root": "ה-ר-ר"},
    219: {"trans": "Esau", "root": "ע-ש-ו"},
    220: {"trans": "And will be", "root": "ה-י-ה"},
    221: {"trans": "to Hashem", "root": "ה-ו-ה"},
    222: {"trans": "the kingdom", "root": "מ-ל-כ"},
    223: {"trans": "And will be", "root": "ה-י-ה"},
    224: {"trans": "Hashem", "root": "ה-ו-ה"},
    225: {"trans": "as King", "root": "מ-ל-כ"},
    226: {"trans": "over", "root": "ע-ל-ל"},
    227: {"trans": "all", "root": "כ-ל-ל"},
    228: {"trans": "the earth", "root": "א-ר-ץ"},
    229: {"trans": "On day", "root": "י-ו-ם"},
    230: {"trans": "that", "root": "ה-ו-א"},
    231: {"trans": "will be", "root": "ה-י-ה"},
    232: {"trans": "Hashem", "root": "ה-ו-ה"},
    233: {"trans": "One", "root": "א-ח-ד"},
    234: {"trans": "and His name", "root": "ש-מ-ם"},
    235: {"trans": "One", "root": "א-ח-ד"}
}

# Apply all mappings
for word_id, mapping in mappings.items():
    wid = f"w{word_id}"
    if wid in data['words']:
        data['words'][wid]['translation'] = mapping['trans']
        data['words'][wid]['shoresh'] = {
            'root': mapping['root'],
            'root_letters': list(mapping['root'].split('-')),
            'meaning': mapping['trans'],
            'word_type': 'noun'
        }

# Write back
with open('data/shirat_hayam_embedded.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Count completion
total = 237
completed = sum(1 for w in data['words'].values() if w['translation'])
print(f"Shirat HaYam: {completed}/{total} words ({100*completed/total:.1f}%)")
print(f"Remaining: {total - completed} words")
